name       : lsb-release
version    : 1.4
release    : 3
source     :
    - http://sourceforge.net/projects/lsb/files/lsb_release/1.4/lsb-release-1.4.tar.gz : 99321288f8d62e7a1d485b7c6bdccf06766fb8ca603c6195806e4457fdf17172
license    : GPL-2.0
summary    : LSB status script
description: |
    The lsb_release script gives information about the Linux Standards Base (LSB) status of the distribution.
builddeps  :
build      : |
    %make
install    : |
    install -D -m 00755 lsb_release %installroot%/usr/bin/lsb_release
    install -d -m 00755 %installroot%/etc/
    echo "LSB_VERSION=1.4" > %installroot%/etc/lsb-release
    echo "DISTRIB_ID=Solus" >> %installroot%/etc/lsb-release
    echo "DISTRIB_DESCRIPTION=\"Solus Operating System betaish\"" >> %installroot%/etc/lsb-release
    echo "DISTRIB_RELEASE=betaish" >> %installroot%/etc/lsb-release
    echo "DISTRIB_CODENAME=betaish" >> %installroot%/etc/lsb-release
